# https://lint.travis-ci.org/
branches:
  only:
  - master
  - test-travis
notifications:
  email: false
git:
  depth: 8
language: c

addons:
  apt:
    packages: [ binutils-mingw-w64, gcc-mingw-w64, p7zip-full, gnupg-curl, dos2unix, realpath ]

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: i686-w64-mingw32-gcc
      services: [ docker ]
      # https://hub.docker.com/_/ubuntu/
      env: DOCKER_IMAGE=ubuntu:rolling
    - os: osx
      osx_image: xcode8.2
      compiler: i686-w64-mingw32-gcc

before_install:
  - >
    if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      brew install p7zip mingw-w64 jq osslsigncode dos2unix gpg gnu-sed || true
      brew install --force-bottle --build-bottle wine || true
    elif [ "$TRAVIS_OS_NAME" = 'linux' ]; then
      time docker pull "${DOCKER_IMAGE}"
      time docker run -it -v "${PWD}:${PWD}" -w "${PWD}" --env-file <(env | grep -E '^(TRAVIS|BINTRAY|GPG|VIRUSTOTAL|CODESIGN)_') \
        "${DOCKER_IMAGE}" sh -c "
        cat /etc/*-release
        ulimit -a
        df -h
        dpkg --add-architecture i386
        apt-get -qq update
        apt-get -qq install \
          curl git make python python-pip \
          binutils-mingw-w64 gcc-mingw-w64 p7zip-full jq dos2unix realpath osslsigncode wine-stable wine64 wine32
        ./_build.sh"
    fi

script:
  - >
    if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      ./_build.sh
    fi
