# https://lint.travis-ci.org/
branches:
  only:
  - master
  - test-travis
language: c
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: i686-w64-mingw32-gcc
      env: HB_CI_THREADS=4
    - os: osx
      osx_image: xcode8.2
      compiler: i686-w64-mingw32-gcc
      env: HB_CI_THREADS=4
addons:
  apt:
    packages: [ binutils-mingw-w64, gcc-mingw-w64, p7zip-full, gnupg-curl, dos2unix, realpath ]
before_install:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      brew update > /dev/null;
      brew install p7zip mingw-w64 jq osslsigncode dos2unix gpg gnu-sed gawk;
      brew cask install wine-devel;
    elif [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$TRAVIS_SUDO" = 'true' ]; then
      sudo dpkg --add-architecture i386;
      sudo apt-get update;
      sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install wine;
    fi;
script:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      WINEHOME='/Applications/Wine Devel.app/Contents/Resources';
      export DYLD_FALLBACK_LIBRARY_PATH="${WINEHOME}/wine/lib:/usr/X11/lib:/usr/lib";
      export PATH="${WINEHOME}/wine/bin:${PATH}";
      export DISPLAY=:88.0; wineboot;
    fi;
    ./_build.sh;
notifications:
  email: false
git:
  submodules: false
  depth: 8
