# https://lint.travis-ci.org/
branches:
  only:
  - master
  - test-travis
notifications:
  email: false
git:
  depth: 8
language: c

addons:
  apt:
    packages: [ binutils-mingw-w64, gcc-mingw-w64, p7zip-full, gnupg-curl, dos2unix, realpath ]

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: i686-w64-mingw32-gcc
      env: HB_CI_THREADS=4
    - os: osx
      osx_image: xcode8.2
      compiler: i686-w64-mingw32-gcc
      env: HB_CI_THREADS=4

before_install:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      brew install p7zip mingw-w64 jq osslsigncode dos2unix gpg gnu-sed || true;
      brew install --force-bottle --build-bottle wine || true;
    elif [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$TRAVIS_SUDO" = 'true' ]; then
      sudo dpkg --add-architecture i386;
      sudo apt-get -qq update;
      sudo apt-get -qq install wine;
    fi;

script:
  - ./_build.sh
